### ISSUE TITLE
I can't access the VPU lab homepage.

### ISSUE THREAD

**Issue by daewon88** [vpulab/Online-Clustering-based-MTMC-Tracking#1]
Dear @elun15 

Hello! Thank you for sharing your great work.

I tried to downlaod the model weights trained on AIC19 S01 scenario at http://www-vpu.eps.uam.es/publications/Online-MTMC-Tracking/ResNet50_AIC20_VERI_layer5_imaugclassifier_latest.pth.tar, but I can't acces it. In addition, it seems that not only the link but also the lab homepage itself is inaccessible. 

Do you know what the issue is? Thanks for the help in advance!
Kind regards,
Daewon

**Comment by elun15** [comment]
dear @daewon88 for a few days we have had problems with the server, which is why the website is not available, but we hope that it will be fixed in the next 1 or 2 days. sorry for the invovenience!
