### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by shijiancode** [vpulab/Online-Clustering-based-MTMC-Tracking#2]

**Comment by shijiancode** [comment]
Hello, the dataset requires a password to download. Can you provide any other download methods

**Comment by jcsma** [comment]
Dear shijiancode,

unfortunately, we cannot distribute the dataset due to copyright issues. Please visit https://www.aicitychallenge.org/ to request the password to download the required dataset. 

Best regards,
Juan Carlos
